openapi: 3.0.0
info:
  title: Web Interfaces API
  version: '1.0'
  contact:
    name: Henrik Kurkela
    url: github.com/henrikkurkela
  description: API for OUAS course Web Interfaces.
servers:
  - url: 'http://localhost:3001'
    description: 'localhost:3001'
paths:
  /api/signup:
    post:
      summary: ''
      operationId: post-api-signup
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  username:
                    type: string
                  updatedAt:
                    type: string
                  createdAt:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: Invalid username.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
                example: Internal server error.
      description: Sign up to the service.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: demouser
                  pattern: '^[a-zA-Z0-9]{1,255}$'
                  minLength: 1
                  maxLength: 255
                email:
                  type: string
                  example: demo@user.com
                  pattern: '^[a-zA-Z0-9.]+@[a-zA-Z]+[.]{1}[a-zA-Z]+$'
                password:
                  type: string
                  example: demopassword
                  pattern: ^. *
              required:
                - username
                - email
                - password
            examples:
              Signup Example:
                value:
                  username: demouser
                  email: demo@user.com
                  password: demopassword
        description: Create user account.
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
          description: 'The server requires content-type application/json for this request. '
      tags:
        - user
  /api/login:
    post:
      summary: ''
      operationId: post-api-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  auth:
                    type: string
              examples:
                Successful login:
                  value:
                    auth: string
        '401':
          description: Incorrect credentials.
          content:
            application/json:
              schema:
                type: string
                example: Incorrect credentials.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: string
                example: Internal server error.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - properties:
                    username:
                      type: string
                      example: demouser
                    password:
                      type: string
                      example: demopassword
                      pattern: ^.*
                  required:
                    - username
                    - password
                - properties:
                    email:
                      type: string
                      pattern: '^[a-zA-Z0-9.]+@[a-zA-Z]+[.]{1}[a-zA-Z]+$'
                      example: demo@user.com
                    password:
                      type: string
                      pattern: ^.*
                      example: demopassword
                  required:
                    - email
                    - password
              type: object
            examples:
              Login with username:
                value:
                  username: demouser
                  password: demopassword
              Login with email:
                value:
                  email: demou@ser.com
                  password: demopassword
      description: Log in to the service.
      tags:
        - user
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
          description: 'The server requires content-type application/json for this request. '
components:
  schemas: {}
tags:
  - name: user
